# Config file for toyako

#####################
## Sample information
sample_id: "E_coli"
# Nanopore data
longreads: "E_coli.fastq.gz"
# QC'ed short reads
# Set qc_short_r1 (and qc_short_r1) to "None" (with quotes) to skip short read polishing
qc_short_r1: "QC_R1.fastq.gz"
qc_short_r2: "QC_R2.fastq.gz"
#####################

## Directory for database installation
db_dir: "/Data/databases/toyako"

## Resources
threads: 40
# Memory in Gigabytes
memory: 200

## Long read QC
# Minimum read length
minlength: 1000
# Minimum average quality (PHRED) score. Q13 is ~5% expected error rate.
minavgquality: 13

## Assembly
# nano-hq (if <5% error) or nano-raw
flye_input_mode: "nano-hq"
# Run Flye in --meta mode? Set to "True", with quotation marks, to use meta mode. Anything else (e.g., "False") will not use meta mode.
flye_meta_mode: "False"
# By default, Flye performs one round of long read polishing after assembly
flye_polishing_rounds: 1

## End repair
# Flye will be used to re-assemble a short region (50-100 kb) around the ends of circular contigs.
#   The re-assembly will be stitched to the original contigs using the circlator merge module.
#   This process repairs an added/missing bases around the contig ends.
# Minimum % ID needed between original and stitch contigs for merging
circlator_merge_min_id: 99
# Minimum hit length (bp) needed between original and stitch contigs for merging
circlator_merge_min_length: 10000
# Minimum distance (bp) between end of original contig and nucmer hit
circlator_merge_ref_end: 100
# Minimum distance (bp) between end of merge contig and nucmer hit
circlator_merge_reassemble_end: 100

## Polishing
# Can set to any model supported by medaka
medaka_model: "r941_min_sup_g507"

## Post-polishing contig filter
# My advice: Only filter by short reads if you have short reads.
#            If you have long reads, filter by long reads (40x minimum depth recommended by Sereika et al., 2022, Nat Methods, for R10.4 flow cells)
meandepth_cutoff_short_read: 10
meandepth_cutoff_long_read: "None"
# Only contigs with this or greater % of bases covered by reads will be kept (e.g., 95%)
evenness_cutoff_short_read: 95
evenness_cutoff_long_read: "None"

## Circularization
# Download the following HMM from Pfam to look for a start gene
# DnaA is PF00308
start_hmm_pfam_id: "PF00308"
hmmsearch_evalue: 1e-40

## Annotation
eggnog_sensmode: "ultra-sensitive"
