channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.*
  - pandas=1.5.*
  - snakemake=8.*
  - mamba=1.5.*
  - wget=1.21.*
  - psutil=5.9.*
  - zip=3.*
  - pip
  - pip:
      - git+https://github.com/rotary-genomics/pungi@develop
