package:
  name: rotary
  version: "0.3.0-beta1"

source:
  path: .

requirements:
  host:
    - python
    - poetry
  run:
    - python=3.9.*
    - pandas=1.4.*
    - snakemake=8.*
    - biopython=1.81
    - mamba=1.5.*
    - wget=1.21.*
    - psutil=5.9.*
    - zip=3.*

build:
  script: poetry install

test:
  commands:
    - rotary -h

about:
  home: https://github.com/jmtsuji/rotary
  license: BSD 3
  license_file: LICENSE