package:
  name: rotary
  version: "0.3.0"

source:
  path: .

requirements:
  host:
    - python
    - poetry
  run:
    - python=3.9.*
    - pandas=1.4.*
    - snakemake=7.*
    - mamba
    - wget
    - ruamel.yaml=0.17.35
    - psutil=5.9.5
    - sh=2.0.*
    - biopython=1.81

build:
  script: poetry install

test:
  commands:
    - rotary -h

about:
  home: https://github.com/jmtsuji/rotary
  license: BSD 3
  license_file: LICENSE